services:
  alert-module:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alert-module
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "alert_module.py"]
      interval: 30s
      timeout: 10s
      retries: 3
