name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting (Ruff)
        run: |
          pytest integration_test_alert_module.py -v
          
      - name: Generate coverage report
        run: |
          coverage run --source=alert_module -m pytest integration_test_alert_module.py
          coverage report -m
          ruff check . --exit-zero

      - name: Run security scan (Bandit)
        run: |
          bandit -r . || true

      - name: Build Docker Image
        run: |
          docker build -t alert-module:latest .

      - name: Push Docker Image to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
          docker tag alert-module:latest lawanlyngdoh/alert-module:latest
          docker push lawanlyngdoh/alert-module:latest
